language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t anddopphoopha/se234-lab10-client .
- docker pull anddopphoopha/se234-lab10-client
- docker pull dto80/234-lab11
service: docker
env:
  global:
  - secure: TSMdijJslyAsTsp7zokx2TG7ZSoMwZZPx/jEKoehj0lgtVSWmdvg7wd8Wx1fWgKxswftgDbkPKZ8JLbYcfQ8elYSfReXxkvud21jBIAaNqxjA4xuzexWvhZE9g++vIpFtiBS24JDrSNT/19/kSR969evsXjXORiElHOvsFmZCTiRBEBJRJSS/WaaW/p639J8HMaYvMku9Fk+OyYgodn8/qW9u52HePZ5WFuOO7NpEZ3zZ33ET5jNweCGGt48TsyWRRFlzi6MULRLerEC0QOVS3nqru1iAc6iV1kBUlol3Dh261jz/B6BPM7w3a20Z3k+QlHiZUpQBILnavtJ5SOYZdLw8x+TnCdhBcQDWQq/Tqq0YWow5KpJynNm22k4NBMaH4pSXD4kMXPySLiRqEWdE7jj2EzO+cJ2DPmZaX/w+F7C/XpvnyfDBF5m47tmZU0PNPsjEbZLOap1WpRAsmaV/eLAj9UUVoLt1HHJuHHaHeyn+EnVUd6oNYyg9w53sJ/FHMBRf1m/gsFSTeAdcoaEnEbmvsEK6xctpoblcrSnFqsGWENWjjYlFrBbmIjdNZWXBXjQC/rdjcrc3nelzr+jHbgGqc2Y01U3wRiaqTqDbP/0QuutaTy/F7YX7dgWceb74lHrKtCDOF4qVYMpqVq8rXDIQsBo1rzEpqwtzTKgPD4=
  - secure: DCZtQaj6y1fnac5zlQH+HfLhhm6Qv9ppcUh+6SGXlDdKH4T9jYrGJxcD3KYXcHj5oLpVDcKplv5HeyT/cyZaCgXJfJfO3M72PEjBZ2uX164Im+ErdBK7jnnKOFXrkacuEvbPe+QGFFTgG5MbgafZLZfTTmEedSqkoVcbu5FZzQP/G9PcwDdurbpO6wOkncTHKeSDQnDGaU11dKObjNz02EB0bd9FWs3trSqwkmSseYj75OKa4oER9OoFLCR6QeyjRRS3nMJtEYFQ0QnuWT8HGkXOYz+EDk8YC3EDdLv1z6n0NXLbEe6vb10fkm3CI/QyUpTvAp83aDEqCTOB8Pu4cJ55ESI/WzQ+xlVbFnEuM8TGW92NPkaetrTuUV/Zecas8JdLRPorAwzQa7ilDCT9NDr4zWv32aAJjVwQguK3H6kVgSYScdHNeW/yLX167/Hp1MH+62PQ8Y3x7FbNboucTExwolR2a21rR26YTHooPXVaPMftH8CS48epz1vAZ5Eu4bzd2cudFWHIitMBnaOAAetrBgGpdrC9HpkNQS1h+asmvQJa5WhxVMz+FC/c7KWOo3Uu9+swJb6zm0KcCefBUs3GoQfiLPS9nzL3IvNm/ty3k6zENVAipwJd6vjv7THD9JlNhdtVCSCqNtypx7hH6zz4O+1eIwvD9Sek1ICPyeY=
